name: Linting .NET
on:
  workflow_run:
    workflows:
      - dotnet
    types:
      - completed

jobs:
  linting:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
       
      - name: Run dotnet format
        run: dotnet format ---check --no-restore --verify-no-changes
